<?php

/**
 * @file
 * Contains field_builder.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function field_builder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the field_builder module.
    case 'help.page.field_builder':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Builds fields from file') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function field_builder_theme() {
  return [
    'field_builder' => [
      'render element' => 'children',
    ],
  ];
}
